# Generated by Django 4.0.7 on 2022-12-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_register',
            new_name='process_register',
        ),
    ]
