# Generated by Django 4.0.7 on 2022-12-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_rename_user_register_process_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='process_team_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
    ]
