# Generated by Django 4.0.7 on 2022-12-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
