# Generated by Django 4.0.7 on 2022-12-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_register_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_register',
        ),
    ]
