# Generated by Django 4.0.7 on 2022-12-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_information',
            old_name='name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user_information',
            old_name='organisation',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user_information',
            old_name='purpose',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user_information',
            name='username',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
