# Generated by Django 4.0.7 on 2022-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_name_user_information_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_credential_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150, null=True)),
                ('pincode', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('file', models.ImageField(upload_to='documents')),
            ],
        ),
        migrations.DeleteModel(
            name='User_information',
        ),
    ]
