# Generated by Django 4.0.7 on 2022-12-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_credential_details_delete_user_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('enquiry', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
