# Generated by Django 4.0.7 on 2022-12-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_credential_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credential_details',
            name='predict',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
