# Generated by Django 4.0.7 on 2022-12-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_credential_details_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_credential_details',
            name='bollean',
            field=models.BooleanField(default=False),
        ),
    ]
