# Generated by Django 4.0.7 on 2022-12-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_detail_boo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain_purpose_register',
            name='boo3',
            field=models.BooleanField(default=False),
        ),
    ]
