# Generated by Django 4.0.7 on 2022-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cipher_register',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='cipher_register',
            old_name='purpose',
            new_name='yourname',
        ),
        migrations.RemoveField(
            model_name='cipher_register',
            name='type',
        ),
        migrations.AddField(
            model_name='cipher_register',
            name='contact',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cipher_register',
            name='password',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
