# Generated by Django 4.0.7 on 2022-12-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipher', '0002_rename_name_cipher_register_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cipher_register',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
