# Generated by Django 4.0.7 on 2022-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cipher', '0003_cipher_register_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='cipher_team_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
    ]
