# Generated by Django 4.0.7 on 2022-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administarator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('id_donor', models.CharField(max_length=150)),
            ],
        ),
    ]
