# Generated by Django 4.0.7 on 2022-12-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administarator', '0002_admin_payslip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_payslip',
            old_name='id_donor',
            new_name='access_id',
        ),
    ]
